LANGUAGES_TO_INT = {'TGLANG_LANGUAGE_AWK': 0,
                    'TGLANG_LANGUAGE_FSHARP': 1,
                    'TGLANG_LANGUAGE_GO': 2,
                    'TGLANG_LANGUAGE_JULIA': 3,
                    'TGLANG_LANGUAGE_LUA': 4,
                    'TGLANG_LANGUAGE_WOLFRAM': 5,
                    'TGLANG_LANGUAGE_PERL': 6,
                    'TGLANG_LANGUAGE_PYTHON': 7,
                    'TGLANG_LANGUAGE_RAKU': 8,
                    'TGLANG_LANGUAGE_ASSEMBLY': 9,
                    'TGLANG_LANGUAGE_ABAP': 10,
                    'TGLANG_LANGUAGE_ACTIONSCRIPT': 11,
                    'TGLANG_LANGUAGE_ADA': 12,
                    'TGLANG_LANGUAGE_APEX': 13,
                    'TGLANG_LANGUAGE_APPLESCRIPT': 14,
                    'TGLANG_LANGUAGE_AUTOHOTKEY': 15,
                    'TGLANG_LANGUAGE_BASIC': 16,
                    'TGLANG_LANGUAGE_C': 17,
                    'TGLANG_LANGUAGE_CSHARP': 18,
                    'TGLANG_LANGUAGE_CPLUSPLUS': 19,
                    'TGLANG_LANGUAGE_CLOJURE': 20,
                    'TGLANG_LANGUAGE_COBOL': 21,
                    'TGLANG_LANGUAGE_COMMON_LISP': 22,
                    'TGLANG_LANGUAGE_CRYSTAL': 23,
                    'TGLANG_LANGUAGE_D': 24,
                    'TGLANG_LANGUAGE_DELPHI': 25,
                    'TGLANG_LANGUAGE_ELIXIR': 26,
                    'TGLANG_LANGUAGE_ELM': 27,
                    'TGLANG_LANGUAGE_ERLANG': 28,
                    'TGLANG_LANGUAGE_FORTH': 29,
                    'TGLANG_LANGUAGE_FORTRAN': 30,
                    'TGLANG_LANGUAGE_HASKELL': 31,
                    'TGLANG_LANGUAGE_IDL': 32,
                    'TGLANG_LANGUAGE_JAVA': 33,
                    'TGLANG_LANGUAGE_JAVASCRIPT': 34,
                    'TGLANG_LANGUAGE_KOTLIN': 35,
                    'TGLANG_LANGUAGE_LOGO': 36,
                    'TGLANG_LANGUAGE_MATLAB': 37,
                    'TGLANG_LANGUAGE_NIM': 38,
                    'TGLANG_LANGUAGE_OBJECTIVE_C': 39,
                    'TGLANG_LANGUAGE_OCAML': 40,
                    'TGLANG_LANGUAGE_PASCAL': 41,
                    'TGLANG_LANGUAGE_PHP': 42,
                    'TGLANG_LANGUAGE_POWERSHELL': 43,
                    'TGLANG_LANGUAGE_PROLOG': 44,
                    'TGLANG_LANGUAGE_R': 45,
                    'TGLANG_LANGUAGE_RUBY': 46,
                    'TGLANG_LANGUAGE_RUST': 47,
                    'TGLANG_LANGUAGE_SCALA': 48,
                    'TGLANG_LANGUAGE_SCHEME': 49,
                    'TGLANG_LANGUAGE_SMALLTALK': 50,
                    'TGLANG_LANGUAGE_SWIFT': 51,
                    'TGLANG_LANGUAGE_TCL': 52,
                    'TGLANG_LANGUAGE_VALA': 53,
                    'TGLANG_LANGUAGE_VBSCRIPT': 54,
                    'TGLANG_LANGUAGE_BATCH': 55,
                    'TGLANG_LANGUAGE_DART': 56,
                    'TGLANG_LANGUAGE_SQL': 57,
                    'TGLANG_LANGUAGE_VERILOG': 58,
                    'TGLANG_LANGUAGE_SAS': 59,
                    'TGLANG_LANGUAGE_TYPESCRIPT': 60,
                    'TGLANG_LANGUAGE_CMAKE': 61,
                    'TGLANG_LANGUAGE_HTML': 62,
                    'TGLANG_LANGUAGE_LATEX': 63,
                    'TGLANG_LANGUAGE_ICON': 64,
                    'TGLANG_LANGUAGE_LISP': 65,
                    'TGLANG_LANGUAGE_HACK': 66,
                    'TGLANG_LANGUAGE_JSON': 67,
                    'TGLANG_LANGUAGE_1S_ENTERPRISE': 68,
                    'TGLANG_LANGUAGE_CSS': 69,
                    'TGLANG_LANGUAGE_SHELL': 70,
                    'TGLANG_LANGUAGE_MARKDOWN': 71,
                    'TGLANG_LANGUAGE_XML': 72,
                    'TGLANG_LANGUAGE_YAML': 73,
                    'TGLANG_LANGUAGE_MAKEFILE': 74,
                    'TGLANG_LANGUAGE_CSV': 75,
                    'TGLANG_LANGUAGE_INI': 76,
                    'TGLANG_LANGUAGE_GRADLE': 77,
                    'TGLANG_LANGUAGE_OTHER': 78,
                    'TGLANG_LANGUAGE_VISUAL_BASIC': 79,
                    'TGLANG_LANGUAGE_ASP': 80,
                    'TGLANG_LANGUAGE_COFFESCRIPT': 81,
                    'TGLANG_LANGUAGE_FIFT': 82,
                    'TGLANG_LANGUAGE_FUNC': 83,
                    'TGLANG_LANGUAGE_GAMS': 84,
                    'TGLANG_LANGUAGE_GRAPHQL': 85,
                    'TGLANG_LANGUAGE_KEYMAN': 86,
                    'TGLANG_LANGUAGE_NGINX': 87,
                    'TGLANG_LANGUAGE_OPENEDGE_ABL': 88,
                    'TGLANG_LANGUAGE_PL_SQL': 89,
                    'TGLANG_LANGUAGE_PROTOBUF': 90,
                    'TGLANG_LANGUAGE_QML': 91,
                    'TGLANG_LANGUAGE_REGEX': 92,
                    'TGLANG_LANGUAGE_TL': 93,
                    'TGLANG_LANGUAGE_UNREALSCRIPT': 94,
                    'TGLANG_LANGUAGE_APACHE_GROOVY': 95,
                    'TGLANG_LANGUAGE_SOLIDITY': 96,
                    'TGLANG_LANGUAGE_TEXTILE': 97,
                    'TGLANG_LANGUAGE_BISON': 98,
                    'TGLANG_LANGUAGE_DOCKER': 99}

LANGUAGES = {
    "TGLANG_LANGUAGE_ASSEMBLY": [';', '\n'],
    "TGLANG_LANGUAGE_CSHARP": ['/*', '*/', '//', '\n'],
    "TGLANG_LANGUAGE_CPLUSPLUS": ['/*', '*/', '//', '\n'],
    "TGLANG_LANGUAGE_CMAKE": ['#[[', ']]', '#', '\n'],
    "TGLANG_LANGUAGE_CSS": ['/*', '*/'],
    "TGLANG_LANGUAGE_FORTRAN": ['!', '\n'],
    "TGLANG_LANGUAGE_HASKELL": ['--', '\n', '{-', '-}'],
    "TGLANG_LANGUAGE_HTML": [''],
    "TGLANG_LANGUAGE_JAVASCRIPT": ['/*', '*/', '//', '\n'],
    "TGLANG_LANGUAGE_JULIA": ['#', '\n', '#=', '=#'],
    "TGLANG_LANGUAGE_LUA": ['--[[', '--]]', '--', '\n'],
    "TGLANG_LANGUAGE_MARKDOWN": ['[', ']: #', '[//]: # (', ')', '[//]: # "', '"', '[]: # (', ')', '[]: # "', '"', ''],
    "TGLANG_LANGUAGE_MAKEFILE": ['#', '\n'],
    "TGLANG_LANGUAGE_PHP": ['/*', '*/', '//', '\n', '<?', '\n'],
    "TGLANG_LANGUAGE_PERL": ['#', '\n', '=begin', '=end'],
    "TGLANG_LANGUAGE_POWERSHELL": ['#', '\n', '<#', '#>'],
    "TGLANG_LANGUAGE_PYTHON": ['#', '\n'],
    "TGLANG_LANGUAGE_RUBY": ['#', '\n', '=begin', '=end'],
    "TGLANG_LANGUAGE_RUST": ['/*', '*/', '//', '\n'],
    "TGLANG_LANGUAGE_SQL": ['/*', '*/', '--', '\n'],
    "TGLANG_LANGUAGE_SCALA": ['/*', '*/', '//', '\n'],
    "TGLANG_LANGUAGE_SHELL": [": '", " '"],
    "TGLANG_LANGUAGE_TYPESCRIPT": ['//', '\n', '/*', '*/'],
    "TGLANG_LANGUAGE_VISUAL_BASIC": ["'", "\n"],
    'TGLANG_LANGUAGE_SCHEME': [''],
    'TGLANG_LANGUAGE_LISP': [''],
    'TGLANG_LANGUAGE_PASCAL': [''],
    'TGLANG_LANGUAGE_MATLAB': [''],
    'TGLANG_LANGUAGE_INI': ['#', '\n'],
    'TGLANG_LANGUAGE_XML': [''],
    'TGLANG_LANGUAGE_APPLESCRIPT': [''],
    'TGLANG_LANGUAGE_WOLFRAM': [''],
    'TGLANG_LANGUAGE_ADA': [''],
    'TGLANG_LANGUAGE_DART': [''],
    'TGLANG_LANGUAGE_VALA': [''],
    'TGLANG_LANGUAGE_GRADLE': [''],
    'TGLANG_LANGUAGE_COBOL': [''],
    'TGLANG_LANGUAGE_CRYSTAL': [''],
    'TGLANG_LANGUAGE_ACTIONSCRIPT': [''],
    'TGLANG_LANGUAGE_AUTOHOTKEY': [''],
    'TGLANG_LANGUAGE_TCL': [''],
    'TGLANG_LANGUAGE_CLOJURE': [''],
    'TGLANG_LANGUAGE_JSON': [''],
    'TGLANG_LANGUAGE_TEXTILE': [''],
    'TGLANG_LANGUAGE_VBSCRIPT': [''],
    'TGLANG_LANGUAGE_AWK': [''],
    'TGLANG_LANGUAGE_YAML': [''],
    'TGLANG_LANGUAGE_IDL': [''],
    'TGLANG_LANGUAGE_KOTLIN': [''],
    'TGLANG_LANGUAGE_CSV': [''],
    'TGLANG_LANGUAGE_APACHE_GROOVY': [''],
    'TGLANG_LANGUAGE_PROLOG': [''],
    'TGLANG_LANGUAGE_SMALLTALK': [''],
    'TGLANG_LANGUAGE_NIM': [''],
    'TGLANG_LANGUAGE_VERILOG': [''],
    'TGLANG_LANGUAGE_DELPHI': [''],
    'TGLANG_LANGUAGE_ABAP': [''],
    'TGLANG_LANGUAGE_OBJECTIVE_C': [''],
    'TGLANG_LANGUAGE_APEX': [''],
    'TGLANG_LANGUAGE_ELIXIR': [''],
    'TGLANG_LANGUAGE_FORTH': [''],
    'TGLANG_LANGUAGE_SAS': [''],
    'TGLANG_LANGUAGE_RAKU': [''],
    'TGLANG_LANGUAGE_SOLIDITY': ['//', '\n'],
    'TGLANG_LANGUAGE_ERLANG': [''],
    'TGLANG_LANGUAGE_OCAML': [''],
    'TGLANG_LANGUAGE_SWIFT': [''],
    'TGLANG_LANGUAGE_ELM': [''],
    'TGLANG_LANGUAGE_LOGO': [''],
    'TGLANG_LANGUAGE_1S_ENTERPRISE': ['//', '\n'],
    'TGLANG_LANGUAGE_GAMS': [''],
    'TGLANG_LANGUAGE_GO': [''],
    'TGLANG_LANGUAGE_LATEX': [''],
    'TGLANG_LANGUAGE_OTHER': [''],
    'TGLANG_LANGUAGE_COMMON_LISP': [''],
    'TGLANG_LANGUAGE_REGEX': [''],
    'TGLANG_LANGUAGE_COFFESCRIPT': [''],
    'TGLANG_LANGUAGE_ICON': [''],
    'TGLANG_LANGUAGE_OPENEDGE_ABL': [''],
    'TGLANG_LANGUAGE_TL': [''],
    'TGLANG_LANGUAGE_HACK': ['<?', '\n'],
    'TGLANG_LANGUAGE_FUNC': [''],
    'TGLANG_LANGUAGE_QML': [''],
    'TGLANG_LANGUAGE_PL_SQL': ['--', '\n'],
    'TGLANG_LANGUAGE_R': [''],
    'TGLANG_LANGUAGE_NGINX': [''],
    'TGLANG_LANGUAGE_D': [''],
    'TGLANG_LANGUAGE_BISON': [''],
    'TGLANG_LANGUAGE_FSHARP': [''],
    'TGLANG_LANGUAGE_BASIC': [''],
    'TGLANG_LANGUAGE_JAVA': [''],
    'TGLANG_LANGUAGE_PROTOBUF': ['//', '\n'],
    'TGLANG_LANGUAGE_UNREALSCRIPT': [''],
    'TGLANG_LANGUAGE_FIFT': [''],
    'TGLANG_LANGUAGE_GRAPHQL': [''],
    'TGLANG_LANGUAGE_KEYMAN': [''],
    'TGLANG_LANGUAGE_DOCKER': [''],
    'TGLANG_LANGUAGE_ASP': [''],
    'TGLANG_LANGUAGE_BATCH': [''],
    'TGLANG_LANGUAGE_C': ['']
}

CODEBERTA_PRETRAINED = "huggingface/CodeBERTa-language-id"
EVALUATE = False
EPOCH = 3
LR = 1e-3
BATCH_SIZE = 128
# print({key: i for i, (key, value) in enumerate(LANGUAGES.items())})
